config/routes.rb
Rails.application.routes.draw do
  resources :videos
  root 'videos#index'

  resources :chats, only: [:index, :create, :show, :update]
  resources :resumes, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/video.rb
class Video < ApplicationRecord

  validates :youtube_id, presence: true
  validates :youtube_id, uniqueness: true

  enum desejo: { quero_muito_muito_ver: 0, quero_muito_ver: 1, quero_ver: 2 }
  enum framework: { rails: 0, nestjs: 1 }
  
  scope :nao_assistidos, -> { where(assistido: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/UpdateChat.rb
class UpdateChat 
  def initialize(chat, message)
    @chat = chat
    @message = message
  end
    
  def update  
    @chat_gpt = ChatGpt.new

    if @chat.open? 
      messages = build_messages
      
      @chat.update(questions_and_answers: @chat.questions_and_answers + [@message])
      
      update_chat
      response = send_gpt_message(messages)

      @chat.update(questions_and_answers: @chat.questions_and_answers + [parse_gpt_response(response)])

      if response.choices[0].message.content.include?(Prompt::StartChat.farewell) 
        
        messages = [{ 'role' => 'system', 'content' => Prompt::ResumeChat.resume_chat(@chat.join_messages) }]
        response = send_gpt_message(messages)
        resume_hash = parse_gpt_response_json(response)
        
        @resume = Resume.create(chat: @chat)
        @chat.update(status: :closed)
        @resume.update(resume_hash) if resume_hash.class == Hash
      end
    end
  end

  private

  def update_chat
    Turbo::StreamsChannel.broadcast_update_to('chats', target: 'ongoing_chat', partial: 'chats/chat', locals: { chat: @chat })
  end

  def build_messages 
    if @chat.questions_and_answers.size == 1 
      messages = [
        { 'role' => 'system', 'content' => @chat.prompt },
        { 'role' => 'assistant', 'content' => @chat.questions_and_answers.first },
        { 'role' => 'user', 'content' => @message }
      ]
    else
      messages = @chat.questions_and_answers.map.with_index { |qa, index| { 'role' => index.even? ? 'user' : 'assistant', 'content' => qa} }
      messages.unshift({ 'role' => 'system', 'content' => @chat.prompt })
      messages << { 'role' => 'user', 'content' => @message}
    end

    messages
  end

  def send_gpt_message(messages)
    gpt_response = @chat_gpt.send_message(messages)
    JSON.parse(gpt_response.to_json, object_class: OpenStruct)
  end

  def parse_gpt_response(response)
    response.choices[0].message.content
  end

  def parse_gpt_response_json(response)
    response_json_markdown = parse_gpt_response(response)
    response_json = response_json_markdown.gsub(/```json\n/, '').gsub(/\n```/, '')
    JSON.parse(response_json, symbolize_names: true)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  def index
    @videos = Video.all.nao_assistidos.order(:created_at)
    if params[:framework].present? 
      @videos = Video.where(framework: params[:framework]).nao_assistidos.order(:created_at)
    end
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  def create
    video_id = params[:video][:youtube_id][/v=([^&]+)/, 1]
    video = Yt::Video.new id: video_id
    titulo = video.title
    canal = video.channel_title

    @video = Video.new(youtube_id: video_id, titulo: titulo, canal: canal, desejo: params[:video][:desejo])

    respond_to do |format|
      if @video.save
        format.html { redirect_to root_path, notice: "Video was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    @video.update(assistido: :true)
    redirect_to root_path, notice: "Video foi marcado como assistido." 
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy!

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:titulo, :canal, :youtube_id, :desejo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estudo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-cyan-950'>
    <main class="container mx-auto px-5 flex justify-center ">
      <%= yield %>
    </main>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, class: "contents") do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :titulo %>
    <%= form.text_field :titulo, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :canal %>
    <%= form.text_field :canal, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :youtube_id %>
    <%= form.text_field :youtube_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :desejo %>
    <%= form.number_field :desejo, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <iframe width="<%= 560*2/3 %>" height="<%= 315*2/3 %>" src=<%="https://www.youtube.com/embed/#{video.youtube_id}"%> title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <div class="flex w-full justify-center my-1 text-center items-center">
    <% (2 - Video.desejos[video.desejo]).times do %>
      <%= image_tag 'fire.svg' , style: 'pointer-events: none;' %>
    <% end %>
    <div class="font-medium mb-1 text-white mx-2"><%= video.id %> - <%= video.titulo %> - <%= video.canal %></div>
    <%= form_with(model: video, url: video_path(video), method: :patch) do |form| %>
      <%= form.submit '😊', class: 'p-1 bg-fuchsia-600 text-white rounded-md ml-2 cursor-pointer' %>
    <% end %>
  </div>
</div>

app/views/videos/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing video</h1>

  <%= render "form", video: @video %>

  <%= link_to "Show this video", @video, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to videos", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/index.html.erb
<div class="w-full">
  <div class="w-full flex justify-center items-center text-center mt-6">
    <div class='flex space-x-6'>
      <div class="font-bold text-4xl text-white">Gerenciador de Videos</div>
      <div class='flex ml-4 text-lg'>
        <div class='w-7 h-7 bg-yellow-200 rounded-full'><%= @videos.count %></div>
      </div>
    </div>
  </div>
  <%= link_to "Adicionar vídeo", new_video_path, class: "fixed top-4 right-4 rounded-lg py-3 px-5 bg-fuchsia-600 text-white font-medium" %>

  <%= form_with(url: videos_path, method: :get, local: true, id: "framework_form") do |form| %>
    <%= select_tag :framework, options_for_select(Video.frameworks.keys.map { |framework| [framework.titleize, framework] }), prompt: "Selecione um Framework", onchange: "this.form.submit();" %>
    <%= submit_tag "Submit", style: "display: none;" %>
  <% end %>

  <div id="videos" class="grid grid-cols-4 gap-4 mt-4">
    <% @videos.each do |video| %>
      <div class="col-span-1">
        <%= render video %>
      </div>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-white">Novo video</h1>

  <%= form_with(model: Video.new, class: "contents") do |form| %>
    <div class="my-5">
      <%= form.label :youtube_id, "Link do youtube", class: 'text-white' %>
      <%= form.text_field :youtube_id %>
    </div>

    <div class="my-5">
      <%= form.label :desejo, class: 'text-white' %>
      <%= form.collection_select :desejo, Video.desejos.keys, :to_s, :humanize, include_blank: true  %>
    </div>

    <div class="my-5">
      <%= form.label :framwork, class: 'text-white' %>
      <%= form.collection_select :framwork, Video.frameworks.keys, :to_s, :humanize, include_blank: true  %>
    </div>

    <div class="inline">
      <%= form.submit 'Adicionar Vídeo',  class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>


  <%= link_to "Voltar", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/videos/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @video %>

    <%= link_to "Edit this video", edit_video_path(@video), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to videos", videos_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this video", @video, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>